server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pulpolog
    static_configs:
      - targets: # tells promtail to look for the logs on the current machine/host
          - localhost
        labels:
          job: pulpolog
          __path__: /tmp/log/*.log

